SET IDENTITY_INSERT Customer oN
INSERT INTO[Customer]([Id],[FirstName],[LastName],[City],[Country],[Phone])
VALUES (94, 'saniay', 'khan','katmandu','nepal','555-4577-878')
INSERT INTO [Customer] ([Id], [FirstName], [LastName],[City],[Country],[Phone])
VALUES (96, 'orang', 'weight','lahor','paksitan','555545-84-66')
INSERT INTO [Customer] ([Id], [FirstName], [LastName],[City],[Country],[Phone])
VALUES (97, 'ninja', 'h2','Lucknow','india','77452-89654')
INSERT INTO [Customer] ([Id], [FirstName], [LastName],[City],[Country],[Phone])
VALUES (98, 'bmw', 'car','UK','USA','4855454-5555')
INSERT INTO [Customer] ([Id], [FirstName], [LastName],[City],[Country],[Phone])
VALUES (99, 'bike', 'zx10r','nagpur','india','555-444-5555')